require(dplyr)
require(tidyr)
features <- read.table("./features.txt")
col_names <- as.character(features)
x_train <- read.table("../UCI HAR Dataset/train/X_train.txt",col.names = col_names)
x_test <- read.table("../UCI HAR Dataset/test/X_test.txt",col.names = col_names)
y_train <- read.table("../UCI HAR Dataset/train/y_train.txt")
y_test <- read.table("../UCI HAR Dataset/test/y_test.txt")
subject_train <- read.table("../UCI HAR Dataset/train/subject_train.txt")
subject_test <- read.table("../UCI HAR Dataset/test/subject_test.txt")
#y_train <- mutate(y_train,V1 = ifelse(V1 == 1, "Walk",V1))
